recovery_behavior_enabled: false
clearing_rotation_allowed: false

DWAPlannerROS:
  max_vel_x: 0.2
  max_vel_theta: 0.6

  acc_lim_theta: 12.0
  acc_lim_x: 5.0

  sim_time: 0.5

  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.15

  dwa: true
  meter_scoring: true

  holonomic_robot: false